### ISSUE TITLE
0.8 cannot post raw body data; works in 0.7

### ISSUE THREAD

**Issue by jconley** [tomas/needle#107] opened 2015-03-10 14:29 UTC
this used to work in 0.7.x:
```
var xml = '<xml>hello</xml>';
require('needle').post('http://hostname.com', xml, { headers: { 'Content-Type': 'application/xml' } }, console.log);
```

but now in 0.8.x, it tries to parse the text as query params only... and throws:
```
TypeError: Invalid object received:<xml>hello</xml>
    at stringify (./node_modules/needle/lib/querystring.js:16:11)
    at Needle.start (./node_modules/needle/lib/needle.js:280:61)
```

if this was intended to be a breaking change, it should be documented in CHANGELOG.

**Comment by tomas** [comment] 2015-03-10 15:26
Nope, not intented. Will check ASAP.

**Comment by tomas** [comment] 2015-03-10 23:07
Are you sure that exact code worked in 0.7? I just checked out v0.7.10 and I get the same result. If you want the raw data to be posted, you should wrap it as a Buffer, eg. `var xml = new Buffer('<xml>hello</xml>');`.

**Comment by jconley** [comment] 2015-03-11 14:06
yes it works. i am testing with node v0.12.0

**Comment by tomas** [comment] 2015-03-24 00:21
I'll give it a shot tonight on node v0.12.0!

**Comment by nopslip** [comment] 2015-04-10 03:29
I'm running into a similar issue with Needle v0.9.1 and Node v0.10.37.  
This:
```var options = { "headers": { 'Accept': 'application/json; charset=UTF-8', 'Content-Type': 'application/json'}};```
```var n4j = {"statements":[{"statement":"CREATE (x) RETURN id(x)"}]};```
```var data = JSON.stringify(n4j);```

```needle.post('http://0.0.0.0:7474/db/data/transaction/commit', data, options,  function (err, resp));```

Throws:
TypeError: Invalid object received:{"statements":[{"statement":"CREATE (x) RETURN id(x)"}]}
    at stringify (/home/newton/neo4j_api/node_modules/needle/lib/querystring.js:16:11)
    at Needle.start (/home/newton/neo4j_api/node_modules/needle/lib/needle.js:279:61)
    
Any ideas? 

Thanks!

**Comment by tomas** [comment] 2015-04-10 04:21
@nopslip: The problem is that Needle's querystring function is receiving a string that doesn't contain any equal signs (e.g. not a querystring) so it doesn't know how to deal with it. You should just pass the original object and let Needle JSON.stringify-it for you, using the `json: true` option. This also takes care of the Accept and Content-Type headers.

```
var n4j = {"statements":[{"statement":"CREATE (x) RETURN id(x)"}]};
needle.post('http://0.0.0.0:7474/db/data/transaction/commit', data, { json: true }, function(err, resp) {
  console.log(err || resp.body);
});
```

**Comment by jconley** [comment] 2015-04-10 04:37
just my 2 cents, but i've never seen any http api that takes a body object an expects a string to be in querystring format.  seems to me it should render string/buffer unmodified. if you expect { json: true } to trigger json stringify, then maybe you should expect { query: true } when the data is a querystring.  or to prevent the possibility of json==true and query==true, use { content: json } or { content: query }

**Comment by tomas** [comment] 2015-04-10 04:39
Yes, I'm actually looking into your example and there was a change between 0.7 and 0.8 that made things a bit inconsistent. I'll let you know when I have a better picture.

**Comment by nopslip** [comment] 2015-04-10 04:51
@tomas That did it! Thank you! Clearly I misunderstood what I was sending. I appreciate the help immensely.

**Comment by tomas** [comment] 2015-04-10 05:24
@jconley I think I have it. I want to add a few specs before pushing this out, but feel free to try out the `request_body` branch and see if it works.

**Comment by mediafreakch** [comment] 2015-08-10 14:03
As I understand the following should work with your fix:
``` needle.post('http://example.com', [123], { json: true }); ```

Any idea when this fix will it be available on npmjs.com?

**Comment by kanayo** [comment] 2015-10-01 02:03
Would be nice to see a fix for this one, need the read_timeout feature but stuck at 0.7.0 because also need raw post data without equal signs.

**Comment by tomas** [comment] 2015-10-02 01:21
I'll be working on this tomorrow! Sorry for the long delay but I've been swamped like hell.

**Closed** 2015-11-12 09:26 UTC
