### ISSUE TITLE
Option {json:true} not working

### ISSUE THREAD

**Issue by Nokel81** [tomas/needle#165] opened 2016-04-06 17:53 UTC
I am using needle for my inter-service http calls and I always use the option `{json:true}` but the out come seems to be not working.
```
{
    "name" : "biil",
    "age" : 20
}
{
    "name" : "biil",
    "age" : "20"
}
```

I send something like the first and get something like the second.

**Comment by tomas** [comment] 2016-04-07 18:36
So the problem is that "age" should be an integer but you're getting a string?

**Comment by Nokel81** [comment] 2016-04-07 18:41
That I am getting a string. But it was actually a placement bug (bodyparser, the one that we were using) was not parsing the "form" header and the data we were sending was for some reason under "form" and not "body". I know don't think that is is a problem with needle. The reason I did was that our http requests where going being sent by needle and on one side it was an integer and as soon as I could on the otherside it was a string

**Comment by tomas** [comment] 2016-04-07 18:43
Ok I'm closing this issue then. If you find anything else feel free to open another issue.

**Closed by tomas** 2016-04-07 18:43 UTC
